FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# beetleapi

Polls is a simple API allowing consumers to view polls and vote in them.

## Some tests [/products]

### List all Products [GET]

Get all available products

+ Response 200 (application/json)

        [
            {
                [
                    "description": "Rice",
                    "published_at": "2015-08-05T08:40:51.620Z",
                    "category": "food",
                    "price": 7.99
                ],
                [
                    "description": "Bean",
                    "published_at": "2015-08-05T08:40:51.620Z",
                    "category": "food",
                    "price": 3.99
                ],
                [
                    "description": "Orange Juice",
                    "published_at": "2015-08-05T08:40:51.620Z",
                    "category": "beverage",
                    "price": 3.24
                ],
                [
                    "description": "Soda",
                    "published_at": "2015-08-05T08:40:51.620Z",
                    "category": "beverage",
                    "price": 3.24
                ]
            }
        ]

## Questions Collection [/questions]

### List All Questions [GET]

+ Response 200 (application/json)

        [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }
